title: INFOSERVIS FCG Ultimate
description: Geopolitical news and insights
theme: minima # Tohle je základní hezká šablona
remote_theme: jekyll/minima

# Nastavení pro zobrazení příspěvků
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
