title: INFOSERVIS FCG Ultimate
description: Geopolitical news and insights
remote_theme: jekyll/minima

# Explicitní definice pluginů
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Toto vynutí správné řazení
incremental: false
